### ISSUE TITLE
Error module.js

### ISSUE THREAD

**Issue by blackbart420** [BrunnerLivio/bitfinex-polybar#1]
Hello,
thank you for this nice module!

I followed your install steps but when I add the module in my polybar it only displays this in polybar : "module.js : 545"

Do you have any idea what the problem could be ? 

PS: your script works fine when I run "node index.js" in console

**Comment by blackbart420** [comment]
Running "node wallet-sum.js" in the polybar directory helped me...

In the "Install files" section, you should add the following line to help stupid guys like me:
cp keys.json $HOME/.config/polybar/

**Comment by BrunnerLivio** [comment]
@blackbart420 
Thanks for the issue. You're right, the README is not documented well. I[ updated it](https://github.com/BrunnerLivio/bitfinex-polybar/commit/4159cf6187998bc349b0e6746b0e506c40ee4447), is it alright now? 

Have fun with the module!

**Comment by blackbart420** [comment]
@BrunnerLivio  yes nice!
It does not need the option "-r" though, I guess cp -f keys.json $HOME/.config/polybar/ should be good enough :)
